# Mesos master role

- name: Configure mesos-master
  template:
    src=value_file.j2
    dest="/etc/mesos-master/{{ item.key }}"
    owner=root
    group=root
    mode=0644
  with_items:
    - { key: "hostname", value: "{{ hostvars[inventory_hostname].ec2_ip_address }}" }
    - { key: "cluster", value: "{{ mesos.cluster }}" }
    - { key: "quorum", value: "{{mesos.quorum}}" }
    - { key: "work_dir", value: "{{mesos.work_dir}}" }
  notify: Restart mesos-master

- name: Disable mesos-slave service
  service:
    name=mesos-slave
    enabled=no
    state=stopped

- name: Enable mesos-master service
  service:
    name=mesos-master
    enabled=yes
    state=started
  tags: service
