---

- name: 'Install sshd'
  apt: pkg={{ item }} state=latest
  with_items:
    - openssh-server

- name: 'Enable and Start sshd service'
  service: name=ssh enabled=yes state=started

- name: 'Install postfix'
  apt: pkg={{ item }} state=latest
  with_items:
    - postfix

- name: 'Enable and Start postfix service'
  service: name=postfix enabled=yes state=started

- name: 'Download GitLab deb repository script'
  get_url: url=https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh dest=/tmp/script.deb.sh

- name: 'Make GitLab deb script executable'
  file: path=/tmp/script.deb.sh mode=0777

- name: 'Install GitLab deb repository'
  shell: /tmp/script.deb.sh

- name: 'Install Gitlab'
  apt: pkg=gitlab-ce state=latest

- name: 'Check if GitLab is already configured'
  stat: path=/var/opt/gitlab
  register: gitlab_configured

- name: 'Configure GitLab'
  shell: 'gitlab-ctl reconfigure'
  when: gitlab_configured.stat.exists == false
