# Common role for all instances

- name: Configuring Timezone
  shell: echo {{ timezone }} > /etc/timezone && dpkg-reconfigure --frontend noninteractive tzdata

- name: Install NTP
  apt:
    pkg=ntp
    state=present
    update_cache=yes
  notify: Restart NTP

- name: Enable NTP service
  service:
    name=ntp
    enabled=yes
    state=started

- name: 'Remove default motd'
  file:
    path=/etc/motd
    state=absent

- name: Configure motd
  copy:
    src=dyn_motd.sh
    dest=/etc/profile.d/dyn_motd.sh
    owner=root
    group=root

- name: 'Set file permissions on motd script'
  file: path=/etc/profile.d/dyn_motd.sh state=touch mode="u=rwx,g=r,o=r"